# https://taskfile.dev

version: '3'

tasks:
  init:
    cmds:
      - brew install pipx
      - pipx ensurepath
      - pipx install poetry
      - poetry install
  run:
    cmds:
      - poetry run python -m main {{.CLI_ARGS}}
  format:
    cmds:
      - poetry run black --line-length 80 main.py
      - poetry run black --line-length 80 src/
  lint:
    cmds:
      - poetry run pylint --rcfile pylintrc main.py
      - poetry run pylint --rcfile pylintrc src/
      - poetry run black --line-length 80 main.py --check
      - poetry run black --line-length 80 src/ --check
  # test:
  #   cmds:
  #     - poetry run python -m pytest
